title: Accessibility Testing Course
description: A complete guide to accessibility testing from manual techniques to AI integration.

remote_theme: "pages-themes/merlot@v0.2.0"
plugins:
  - jekyll-remote-theme
  